export const START_FETCHING_USERS = 'START_FETCHING_USERS';
export const FAIL_FETCHING_USERS = 'FAIL_FETCHING_USERS';
export const SUCCESSFUL_FETCHING_USERS = 'SUCCESSFUL_FETCHING_USERS';

export const START_FETCHING_USER = 'START_FETCHING_USER';
export const FAIL_FETCHING_USER = 'FAIL_FETCHING_USER';
export const SUCCESSFUL_FETCHING_USER = 'SUCCESSFUL_FETCHING_USER';

export const CLEANUP_FETCHED_USER = 'CLEANUP_FETCHED_USER';